Drop the bitflags dependency
serpent-os/moss pull request #148
Opened 2024-02-28 09:48 UTC by livingsilver94

This PR replaces the bitflags functionality with an in-house implementation.

I think we all agree on reducing the number of dependencies where it makes sense, and I also think bitflags is one dependency worth removing. It is based on a `macro_rule` which is able to escape the original Rust syntax (think of that `: u8` syntax to specify that flags are bytes. That's a C++ notation!), making code a little confusing. `macro_rules` have too much freedom of toying with the code, IMO.

The new `Flags` struct is a type-safe and value-safe collection of flags. It is not possible to build an invalid collection of Flags. The idea is based on `std::fs::OpenOptions`.

Did you note that `bits()` private method? That's a micro-optimization. While I could implement the `contains()` method using pure boolean logic, with Compiler Explorer I noticed that that would introduce conditional jumps in the assembly. For the sake of the CPU pipeline, I chose to convert the single flags back into an integer for the comparison, thus avoiding jumps altogether.

2024-02-28 16:06 UTC, tarkah requested changes
Awesome! For me the win is not having LSP breakdown when doing go-to-definition on `contains` or any of the other implementations due to macro usage. Plus it's easier to reason about in general, I like. 

One small comment around builder pattern.

2024-02-28 16:06 UTC, tarkah commented on crates/moss/src/package/mod.rs
> +            ..*self
Builder pattern is typically either `&mut self` or `self`. I think for our usage `self` makes the most sense, and you'll eliminate the `* / Copy`

2024-02-28 17:08 UTC, livingsilver94 commented on crates/moss/src/package/mod.rs
> +            ..*self
Makes sense! That means that `self` is a copy, instead of a consumption of the object?

2024-02-28 17:11 UTC, livingsilver94 commented on crates/moss/src/package/mod.rs
> +            ..*self
Because Self implements Copy, I mean.

2024-02-28 18:08 UTC, tarkah commented on crates/moss/src/package/mod.rs
> +            ..*self
Yeah apologies, we're still copying here

2024-02-28 18:12 UTC, livingsilver94 commented
Oops, made a mess with git history. Fixing.

2024-02-29 13:48 UTC, tarkah approved these changes

2024-03-05 21:38 UTC, tarkah approved these changes

2024-03-05 21:41 UTC, merged